name: Crear un ZIP del directorio 

on: 
  push: 
    branches:
      - main1
jobs:
  crear-zip:
    runs-on: ubuntu-latest
    steps:
    
      - name: Step 1 - Crear directorios alfa
        run: mkdir alfa
        
      - name: Step 2 - Adicionar archivos al directorio alfa
        run: |
          cd alfa
          echo 'Mensaje alfa 1'    > alfa01.html
          echo 'Mensaje alfa 2'    > alfa02.html
          cd ..
          
      - name: Step 3 - Zip directorio alfa
        run: zip -r alfa.zip alfa
                           
      - name: Step 4 - Verificacion de la creacion del archivo ZIP
        run: ls -la
