name: Ejecucion de comandos en paralelo

on: 
  push: 
    branches:
      - main
 
jobs:
  comandos-paralelo:
    runs-on: ubuntu-latest
    steps:
    
    - name: Step 1 - Listado de directorios
      run: ls -la
      
    - name: Step 2 - Creacion de directorios
      run: mkdir documentos
      
    - name: Step 3 - Creacion de archivos en directorio
      run: |
        cd documentos
        echo 'Primer mensaje'     > archivo01.txt
        echo 'Segundo mensaje'     > archivo02.txt
        echo 'Tercer mensaje'     > archivo03.txt
        cd ..
        
     - name: Step 4 - Listado de directorios y archivos
       run: ls -la documentos
       
     - name: Step 5 - Visualizacion de contenidos
       run: |
         cd documentos
         cat archivo01.txt
         cat archivo02.txt
         cat archivo03.txt
      
      
      
